name: LintPR's & Dependabot automerge

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-linters-pull-request:
    name: Run linter for PR's
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          continue_on_error: false
          eslint: true
          auto_fix: false

  auto-approve:
    name: Auto approve
    runs-on: ubuntu-latest
    # Not requiring successful prior job
    if: ${{ always() }}
    needs: [run-linters-pull-request]
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  automerge:
    name: Auto merge
    runs-on: ubuntu-latest
    # jobs run in parallel by default, automerge needs autoapprove as a prerequisite
    needs: autoapprove
    steps:
      - uses: pascalgn/automerge-action@v0.15.3
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          # Merges those PRs labelled "dependencies" only
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
