---
# This workflow handels the release of a new version.

name: Publish Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  buildRelease:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python enviroment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitignore_parser

      - name: Create pyromod and zip files
        run: |
          python .github/build_scripts/make_pyromod.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PYROMOD_MOD_NAME }} v${{ env.PYROMOD_MOD_VERSION }}
          tag_name: v${{ env.PYROMOD_MOD_VERSION }}
          files: |
            ${{ env.PYROMOD_PYROMOD_FILE_PATH }}
            ${{ env.PYROMOD_ZIP_FILE_PATH }}
          generate_release_notes: true

  # TODO "This action does not generate PKGBUILD for you, you must generate it yourself (e.g. by using actions before this action)."
  #  https://github.com/search?o=desc&q=github-actions-deploy-aur+language%3AYAML&s=indexed&type=Code
  #  labels: should have
  #  assignees: IlanFrumer
  aur-publish:
    # https://aur.archlinux.org/packages/0ad-boongui
    name: AUR Release
    needs: [buildRelease]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.5.0
        with:
          pkgname: 0ad-boongui
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
